apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-prometheus-app
  labels:
    app: flask-prometheus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-prometheus-app
  template:
    metadata:
      labels:
        app: flask-prometheus-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
    spec:
      containers:
      - name: flask-prometheus-app
        image: kodekloud/flask-prometheus-app:2
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flask-prometheus-app-service
  labels:
    app: flask-prometheus-app
spec:
  selector:
    app: flask-prometheus-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-prometheus-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-prometheus-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "100m"